Repository thirvusoft/paver_sgp, pull requests merged in 2022-08, with the labels that each got.

#208 CHECKIN Alert
  ganapathy_pavers/custom/py/employee_atten_tool.py
  ganapathy_pavers/custom/py/ts_employee_atten_tool.js
  ganapathy_pavers/ganapathy_pavers/doctype/ts_employee_attendance_tool/ts_employee_attendance_tool.json
Labels: enhancement, good first issue, bug fix 🛠️

#210 CHECKIN Alert
  ganapathy_pavers/custom/py/ts_employee_atten_tool.js
  ganapathy_pavers/hooks.py
Labels: bug

#207 Site work customizations and filters in BOM
  ganapathy_pavers/custom/js/bom.js
  ganapathy_pavers/custom/js/site_work.js
  ganapathy_pavers/custom/py/defaults.py
  ganapathy_pavers/custom/py/site_work.py
  ganapathy_pavers/hooks.py
  ganapathy_pavers/patches.txt
  ganapathy_pavers/patches/sitework_patch.py
  ganapathy_pavers/utils/py/site_work.py
Labels: enhancement, bug fix 🛠️

#206 Mileage calculate
  ganapathy_pavers/custom/py/vehicle_log.py
  ganapathy_pavers/ganapathy_pavers/custom/maintenance_details.json
  ganapathy_pavers/ganapathy_pavers/custom/vehicle_log.json
  ganapathy_pavers/ganapathy_pavers/custom/vehicle_service.json
  ganapathy_pavers/ganapathy_pavers/doctype/maintenance_details/maintenance_details.json
  ganapathy_pavers/ganapathy_pavers/doctype/vehicle_settings/vehicle_settings.json
  ganapathy_pavers/hooks.py
Labels: enhancement, bug fix 🛠️

#213 Job worker advance in site work
  ganapathy_pavers/custom/js/site_work.js
  ganapathy_pavers/custom/py/sales_order.py
  ganapathy_pavers/custom/py/site_work.py
  ganapathy_pavers/ganapathy_pavers/custom/employee_advance.json
  ganapathy_pavers/ganapathy_pavers/doctype/additional_costs/additional_costs.json
Labels: enhancement

#219 vehicle log hours
  ganapathy_pavers/custom/js/vehicle_log.js
  ganapathy_pavers/custom/py/vehicle_log.py
  ganapathy_pavers/ganapathy_pavers/custom/maintenance_details.json
  ganapathy_pavers/ganapathy_pavers/custom/vehicle.json
  ganapathy_pavers/ganapathy_pavers/custom/vehicle_log.json
  ganapathy_pavers/ganapathy_pavers/custom/vehicle_service.json
  ganapathy_pavers/ganapathy_pavers/doctype/ts_email_id/__init__.py
  ganapathy_pavers/ganapathy_pavers/doctype/ts_email_id/ts_email_id.json
  ganapathy_pavers/ganapathy_pavers/doctype/ts_email_id/ts_email_id.py
  ganapathy_pavers/ganapathy_pavers/doctype/ts_vehicle_service/ts_vehicle_service.json
  ganapathy_pavers/ganapathy_pavers/doctype/vehicle_settings/vehicle_settings.json
  ganapathy_pavers/hooks.py
Labels: bug, enhancement

#222 Employee attendance
  ganapathy_pavers/custom/py/employee.py
  ganapathy_pavers/custom/py/employee_checkin.py
  ganapathy_pavers/ganapathy_pavers/custom/attendance.json
  ganapathy_pavers/ganapathy_pavers/print_format/salary_slip/salary_slip.json
  ganapathy_pavers/hooks.py
Labels: enhancement

#226 attendance cancel
  ganapathy_pavers/custom/py/employee_atten_tool.py
  ganapathy_pavers/hooks.py
Labels: enhancement

#220 OT and Total Working Hours
  ganapathy_pavers/custom/py/employee.py
  ganapathy_pavers/ganapathy_pavers/custom/attendance.json
  ganapathy_pavers/ganapathy_pavers/custom/salary_slip.json
  ganapathy_pavers/hooks.py
  ganapathy_pavers/utils/py/payroll_entry.py
Labels: enhancement

#237 Total Row for Report Builder
  ganapathy_pavers/backup/report_view.js
  ganapathy_pavers/custom/py/reportview.py
Labels: enhancement
