Repository thirvusoft/paver_sgp, pull requests merged in 2022-07, with the labels that each got.

#124 Sales Order Customization
  ganapathy_pavers/custom/js/sales_order.js
  ganapathy_pavers/ganapathy_pavers/custom/packed_item.json
  ganapathy_pavers/ganapathy_pavers/custom/sales_order.json
  ganapathy_pavers/ganapathy_pavers/custom/sales_order_item.json
  ganapathy_pavers/ganapathy_pavers/doctype/item_detail_compound_wall/item_detail_compound_wall.json
Labels: enhancement

#125 Delivery Trip Issue Fix
  ganapathy_pavers/ganapathy_pavers/print_format/ts_delivery_trip/ts_delivery_trip.json
Labels: enhancement

#129 Slab
  ganapathy_pavers/custom/js/sales_order.js
  ganapathy_pavers/custom/js/site_work.js
  ganapathy_pavers/custom/py/sales_invoice.py
  ganapathy_pavers/custom/py/sales_order.py
  ganapathy_pavers/ganapathy_pavers/doctype/item_detail_compound_wall/item_detail_compound_wall.json
Labels: enhancement

#131 lead
  ganapathy_pavers/custom/py/lead.py
  ganapathy_pavers/ganapathy_pavers/custom/quotation_item.json
  ganapathy_pavers/hooks.py
Labels: enhancement

#130 Vehicle and Vehicle Log Customization
  ganapathy_pavers/hooks.py
  ganapathy_pavers/utils/py/maintenance_details.py
  ganapathy_pavers/utils/py/vehicle.py
  ganapathy_pavers/utils/py/vehicle_log.py
Labels: enhancement

#136 TS Customer Ledger Summary
  ganapathy_pavers/ganapathy_pavers/report/ts_customer_ledger_summary/__init__.py
  ganapathy_pavers/ganapathy_pavers/report/ts_customer_ledger_summary/ts_customer_ledger_summary.js
  ganapathy_pavers/ganapathy_pavers/report/ts_customer_ledger_summary/ts_customer_ledger_summary.json
  ganapathy_pavers/ganapathy_pavers/report/ts_customer_ledger_summary/ts_customer_ledger_summary.py
Labels: enhancement

#137 Delivery Amount
  ganapathy_pavers/ganapathy_pavers/report/ts_customer_ledger_summary/ts_customer_ledger_summary.py
Labels: enhancement

#143 Report naming
  ganapathy_pavers/custom/js/employee_atten_tool.js
  ganapathy_pavers/ganapathy_pavers/report/ts_customer_receivable_summary/__init__.py
  ganapathy_pavers/ganapathy_pavers/report/ts_customer_receivable_summary/ts_customer_receivable_summary.js
  ganapathy_pavers/ganapathy_pavers/report/ts_customer_receivable_summary/ts_customer_receivable_summary.json
  ganapathy_pavers/ganapathy_pavers/report/ts_customer_receivable_summary/ts_customer_receivable_summary.py
  ganapathy_pavers/hooks.py
Labels: enhancement

#139 Check In
  ganapathy_pavers/custom/js/employee_atten_tool.js
  ganapathy_pavers/hooks.py
Labels: enhancement

#141 Notifications for Purchase order
  ganapathy_pavers/custom/py/purchase_order.py
  ganapathy_pavers/hooks.py
  ganapathy_pavers/utils/py/purchase_order.py
Labels: enhancement

#152 Vehicle and Vehicle log fixes and rework
  ganapathy_pavers/custom/js/vehicle_log_service.js
  ganapathy_pavers/custom/py/vehicle_log.py
  ganapathy_pavers/ganapathy_pavers/doctype/ts_vehicle_service/ts_vehicle_service.json
  ganapathy_pavers/hooks.py
  ganapathy_pavers/utils/py/vehicle_log.py
Labels: bug, enhancement

#154 Employee Checkin, Checkout, attendance
  ganapathy_pavers/custom/js/employee_atten_tool.js
  ganapathy_pavers/custom/py/employee_atten_tool.py
  ganapathy_pavers/custom/py/property_setter.py
  ganapathy_pavers/custom/py/ts_employee_atten_tool.js
  ganapathy_pavers/ganapathy_pavers/doctype/employee_advance_tool/employee_advance_tool.py
  ganapathy_pavers/ganapathy_pavers/doctype/ts_emloyee_attendance_tool/__init__.py
  ganapathy_pavers/ganapathy_pavers/doctype/ts_emloyee_attendance_tool/test_ts_emloyee_attendance_tool.py
  ganapathy_pavers/ganapathy_pavers/doctype/ts_emloyee_attendance_tool/ts_emloyee_attendance_tool.js
  ganapathy_pavers/ganapathy_pavers/doctype/ts_emloyee_attendance_tool/ts_emloyee_attendance_tool.json
  ganapathy_pavers/ganapathy_pavers/doctype/ts_emloyee_attendance_tool/ts_emloyee_attendance_tool.py
  ganapathy_pavers/ganapathy_pavers/doctype/ts_employee_details/__init__.py
  ganapathy_pavers/ganapathy_pavers/doctype/ts_employee_details/ts_employee_details.json
  ganapathy_pavers/ganapathy_pavers/doctype/ts_employee_details/ts_employee_details.py
  ganapathy_pavers/hooks.py
Labels: enhancement

#162 Vehicle Settings Created
  ganapathy_pavers/custom/js/vehicle_log.js
  ganapathy_pavers/ganapathy_pavers/custom/maintenance_details.json
  ganapathy_pavers/ganapathy_pavers/custom/vehicle.json
  ganapathy_pavers/ganapathy_pavers/custom/vehicle_log.json
  ganapathy_pavers/ganapathy_pavers/custom/vehicle_service.json
  ganapathy_pavers/ganapathy_pavers/doctype/vehicle_settings/__init__.py
  ganapathy_pavers/ganapathy_pavers/doctype/vehicle_settings/test_vehicle_settings.py
  ganapathy_pavers/ganapathy_pavers/doctype/vehicle_settings/vehicle_settings.js
  ganapathy_pavers/ganapathy_pavers/doctype/vehicle_settings/vehicle_settings.json
  ganapathy_pavers/ganapathy_pavers/doctype/vehicle_settings/vehicle_settings.py
Labels: enhancement

#166 New
  ganapathy_pavers/custom/js/vehicle_log.js
  ganapathy_pavers/custom/py/employee_atten_tool.py
  ganapathy_pavers/custom/py/ts_employee_atten_tool.js
  ganapathy_pavers/ganapathy_pavers/custom/vehicle.json
  ganapathy_pavers/ganapathy_pavers/custom/vehicle_log.json
  ganapathy_pavers/ganapathy_pavers/doctype/ts_emp_checkin_cancel_table/__init__.py
  ganapathy_pavers/ganapathy_pavers/doctype/ts_emp_checkin_cancel_table/ts_emp_checkin_cancel_table.json
  ganapathy_pavers/ganapathy_pavers/doctype/ts_emp_checkin_cancel_table/ts_emp_checkin_cancel_table.py
  ganapathy_pavers/ganapathy_pavers/doctype/ts_employee_attendance_tool/__init__.py
  ganapathy_pavers/ganapathy_pavers/doctype/ts_employee_attendance_tool/test_ts_employee_attendance_tool.py
  ganapathy_pavers/ganapathy_pavers/doctype/ts_employee_attendance_tool/ts_employee_attendance_tool.js
  ganapathy_pavers/ganapathy_pavers/doctype/ts_employee_attendance_tool/ts_employee_attendance_tool.json
  ganapathy_pavers/ganapathy_pavers/doctype/ts_employee_attendance_tool/ts_employee_attendance_tool.py
  ganapathy_pavers/hooks.py
Labels: enhancement

#171 Employee checkout update
  ganapathy_pavers/custom/py/employee_atten_tool.py
  ganapathy_pavers/custom/py/ts_employee_atten_tool.js
  ganapathy_pavers/ganapathy_pavers/custom/employee_checkin.json
  ganapathy_pavers/ganapathy_pavers/doctype/ts_employee_attendance_tool/ts_employee_attendance_tool.json
Labels: enhancement

#172 Vehicle log
  ganapathy_pavers/custom/js/delivery_note.js
  ganapathy_pavers/custom/py/delivery_note.py
  ganapathy_pavers/custom/py/vehicle_log.py
  ganapathy_pavers/ganapathy_pavers/custom/delivery_note.json
  ganapathy_pavers/hooks.py
Labels: enhancement

#176 Automatically fill up UOM table and Item field customizations
  ganapathy_pavers/custom/js/item.js
  ganapathy_pavers/hooks.py
  ganapathy_pavers/utils/py/item.py
Labels: enhancement

#179 purchase receipt raw material warehouse
  ganapathy_pavers/custom/py/purchase_receipt.py
  ganapathy_pavers/hooks.py
Labels: enhancement

#177 Vehicle Log and Vehicle minor fixes
  ganapathy_pavers/custom/py/vehicle_log.py
  ganapathy_pavers/ganapathy_pavers/doctype/ts_vehicle_service/ts_vehicle_service.json
  ganapathy_pavers/ganapathy_pavers/doctype/vehicle_log_service/vehicle_log_service.json
Labels: bug, enhancement

#180 Employee Working Hours in Employee And Total Working Hours in salary …
  ganapathy_pavers/custom/py/employee.py
  ganapathy_pavers/ganapathy_pavers/print_format/quotation/quotation.json
  ganapathy_pavers/hooks.py
  ganapathy_pavers/utils/py/payroll_entry.py
Labels: enhancement

#184 employee attendance, hour field missing
  ganapathy_pavers/ganapathy_pavers/custom/attendance.json
  ganapathy_pavers/ganapathy_pavers/custom/salary_slip.json
Labels: bug, enhancement

#186 Minor Fix in Item doctype
  ganapathy_pavers/utils/py/item.py
Labels: bug, enhancement

#187 Minor Fix in Item table
  ganapathy_pavers/utils/py/item.py
Labels: bug, enhancement

#189 Print statements removed
  ganapathy_pavers/custom/py/site_work.py
Labels: enhancement

#190 Minor fixes and patches
  ganapathy_pavers/hooks.py
  ganapathy_pavers/patches.txt
  ganapathy_pavers/patches/item_patches1.py
  ganapathy_pavers/patches/patches.py
  ganapathy_pavers/utils/py/item.py
Labels: bug, enhancement

#191 sw fixes
  ganapathy_pavers/custom/py/sales_order.py
Labels: bug, enhancement

#192 Quotation print format
  ganapathy_pavers/ganapathy_pavers/print_format/quotation/quotation.json
Labels: enhancement

#193 Quotation Print format fixes
  ganapathy_pavers/ganapathy_pavers/print_format/quotation/quotation.json
Labels: enhancement

#196 print format journal entry credit note
  ganapathy_pavers/ganapathy_pavers/print_format/ts_journal_entry_credit_note/__init__.py
  ganapathy_pavers/ganapathy_pavers/print_format/ts_journal_entry_credit_note/ts_journal_entry_credit_note.json
Labels: enhancement

#197 Maintenance details, Add on and Expiry date customizations
  ganapathy_pavers/custom/js/vehicle.js
  ganapathy_pavers/ganapathy_pavers/custom/maintenance_details.json
  ganapathy_pavers/ganapathy_pavers/custom/vehicle.json
Labels: enhancement

#198 Chores:bug fix
  ganapathy_pavers/ganapathy_pavers/report/job_worker___report/job_worker___report.py
Labels: bug fix 🛠️

#200 biometric buffer time
  ganapathy_pavers/ganapathy_pavers/doctype/biometric_settings/__init__.py
  ganapathy_pavers/ganapathy_pavers/doctype/biometric_settings/biometric_settings.js
  ganapathy_pavers/ganapathy_pavers/doctype/biometric_settings/biometric_settings.json
  ganapathy_pavers/ganapathy_pavers/doctype/biometric_settings/biometric_settings.py
  ganapathy_pavers/ganapathy_pavers/doctype/biometric_settings/test_biometric_settings.py
Labels: enhancement

#199 delivery note field customize
  ganapathy_pavers/custom/js/delivery_note.js
  ganapathy_pavers/custom/js/vehicle.js
  ganapathy_pavers/custom/py/journal_entry.py
  ganapathy_pavers/ganapathy_pavers/custom/delivery_note.json
  ganapathy_pavers/ganapathy_pavers/custom/journal_entry.json
  ganapathy_pavers/ganapathy_pavers/custom/journal_entry_account.json
  ganapathy_pavers/ganapathy_pavers/print_format/ts_journal_entry_credit_note/ts_journal_entry_credit_note.json
  ganapathy_pavers/hooks.py
Labels: bug fix 🛠️

#201 Vignesh dev filters
  ganapathy_pavers/custom/js/employee.js
  ganapathy_pavers/custom/py/ts_employee_atten_tool.js
  ganapathy_pavers/hooks.py
Labels: enhancement
